#POST https://blooming-ocean-50821.herokuapp.com/api/persons
POST http://localhost:3002/api/persons
content-type: application/json

{
    "name": "a",
    "number": "3 939393"
}

###

PUT http://localhost:3002/api/persons/602901507ac9a4b7cabf722e
content-type: application/json

{
    "name": "CHANGED",
    "number": "333333333333"
}